version: "3.9"
services:
  rabbit:
    container_name: rabbit
    image: rabbitmq:3
    network_mode: host
    volumes:
      - type: bind
        source: ./api
        target: /workspaces/rabbit
  api:
    container_name: api
    tty: true
    image: node
    network_mode: host
    volumes:
      - type: bind
        source: ./api
        target: /workspaces/api

    depends_on:
      - rabbit
  app:
    container_name: app
    tty: true
    image: google/dart:latest
    network_mode: host
    volumes:
      - type: bind
        source: ./app
        target: /workspaces/app
    depends_on:
      - rabbit
      - api

volumes:
  shared:
